version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"

  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "banco"
    ports:
      - "5432:5432"
    volumes:
      - /home/smigou/enioj/Util/bdPostgres:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge